services:
  pgold_db:
    image: postgres:16-alpine
    container_name: pgold_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pgold
      POSTGRES_USER: pgold_user
      POSTGRES_PASSWORD: pgold_pass
    ports:
      - "5432:5432"
    volumes:
      - pgold_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgold_db_data: